package com.example.springhibernatedemo.pojo;
// Generated Feb 21, 2021 5:08:38 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "jdbcapi")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7326958129854489618L;
	private Integer id;
	private Country country;
	private String name;
	private String phoneno;
	private String deptit;
	private String status;
	private Date createdDtm;
	private String createdBy;
	private Date updatedDtm;
	private String updatedBy;

	public Employee() {
	}

	public Employee(String name, String phoneno, String deptit, String status, Date createdDtm, String createdBy,
			Date updatedDtm, String updatedBy) {
		this.name = name;
		this.phoneno = phoneno;
		this.deptit = deptit;
		this.status = status;
		this.createdDtm = createdDtm;
		this.createdBy = createdBy;
		this.updatedDtm = updatedDtm;
		this.updatedBy = updatedBy;
	}

	public Employee(Country country, String name, String phoneno, String deptit, String status, Date createdDtm,
			String createdBy, Date updatedDtm, String updatedBy) {
		this.country = country;
		this.name = name;
		this.phoneno = phoneno;
		this.deptit = deptit;
		this.status = status;
		this.createdDtm = createdDtm;
		this.createdBy = createdBy;
		this.updatedDtm = updatedDtm;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cid")
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "Name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Phoneno", nullable = false, length = 45)
	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	@Column(name = "Deptit", nullable = false, length = 45)
	public String getDeptit() {
		return this.deptit;
	}

	public void setDeptit(String deptit) {
		this.deptit = deptit;
	}

	@Column(name = "Status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDTm", nullable = false, length = 19)
	public Date getCreatedDtm() {
		return this.createdDtm;
	}

	public void setCreatedDtm(Date createdDtm) {
		this.createdDtm = createdDtm;
	}

	@Column(name = "CreatedBy", nullable = false, length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDTm", nullable = false, length = 19)
	public Date getUpdatedDtm() {
		return this.updatedDtm;
	}

	public void setUpdatedDtm(Date updatedDtm) {
		this.updatedDtm = updatedDtm;
	}

	@Column(name = "UpdatedBy", nullable = false, length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
